### ISSUE TITLE
Bump minimum Wagtail/Django/Python versions

### ISSUE THREAD

**Issue by tomusher** [wagtail/wagtail-ai#14]
Once #11 is complete, we will be relying on APIs only present in Wagtail 5.1+.

To avoid having to keep Draftail hacks in the codebase and so we have a 'modern' set of dependencies on which to build the future of the package; I propose we bump the minimum supported versions to:

- Wagtail 5.2 (LTS)
- Django 4.2 (LTS)
- Python 3.11

**Comment by tm-kn** [comment]
https://github.com/wagtail/wagtail-ai/pull/27#discussion_r1399000659

- [ ] Remove the target Python version for Black in the pre-commit config and add the required Python version (3.11) in `pyproject.toml`.
