### ISSUE TITLE
Support managing rich text prompts from Wagtail admin

### ISSUE THREAD

**Issue by tomusher** [wagtail/wagtail-ai#18]
Rich text prompts are currently managed using the `WAGTAIL_AI_PROMPTS` setting. It would be a nice for users if these prompts were instead stored in the database and they could be created/edited from the Wagtail admin.

This would allow easier customisation for cases such as defining a tone of voice, enforcing site-specific rules, etc.

In two minds about whether we should continue to support the `WAGTAIL_AI_PROMPTS` setting, but my initial inclination would be to *only* support database-managed prompts.

**Comment by zerolab** [comment]
I agree with db-only prompts. 
Q: should we create a migration step that would set the new db-managed prompts from `WAGTAIL_AI_PROMPTS` ?

**Comment by tm-kn** [comment]
>  Q: should we create a migration step that would set the new db-managed prompts from WAGTAIL_AI_PROMPTS ?

Yep, default prompts sound good so it works out of the box.

**Comment by tomusher** [comment]
Seeding some default prompts would definitely be nice, although I think @zerolab's point is more about migrating a user's customised prompts to the database if they have set their own `WAGTAIL_AI_PROMPTS` - certainly sounds like this would be a nice thing to do.

**Comment by Morsey187** [comment]
PR open here https://github.com/wagtail/wagtail-ai/pull/38
