### ISSUE TITLE
The proccess view should use form validation

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail-ai#23]
Right now we don't do any validation on the process endpoint. A massive ick as it does not feel like an adequate user/external input validation.

https://github.com/wagtail/wagtail-ai/blob/13e479cd1f9bfbaa7f1531a5d3ab0faea60c4da3/src/wagtail_ai/views.py#L77-L94

We want to replace the `HttpRequest.POST` references and replace it with a Django form validation.

We should wrap this into a Django form to benefit from any Django defaults and put good practice in place for the future.

**Comment by kituuu** [comment]
Can I work on this @tm-kn ?

**Comment by tomusher** [comment]
Hi @kituuu - thanks for offering to contribute!

Feel free to work on this one if you'd like to.

**Comment by kituuu** [comment]
Hey, @tomusher, can you tell me where I can find contribution instructions and dev environment setup instructions? 
Current contribution.md is empty... (https://github.com/wagtail/wagtail-ai/blob/main/CONTRIBUTING.md)

**Comment by zerolab** [comment]
@kituuu sorry, I ended up sorting this out in #48.

Thank you for point out that CONTRIBUTION.md is empty. Will try to add something

**Comment by kituuu** [comment]
> @kituuu sorry, I ended up sorting this out in #48.
> 
> Thank you for point out that CONTRIBUTION.md is empty. Will try to add something

Np, if there are any other issues. Pls let me know.
