### ISSUE TITLE
Should we be assigning JS variables to the window global?

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail-ai#24]
https://github.com/wagtail/wagtail-ai/blob/04bc8c3d4a88a20dd6f1d6642ddbed758035d5cd/src/wagtail_ai/wagtail_hooks.py#L84-L97

I think we could use Django's json_script instead (https://github.com/django/django/blob/61c305f298da1b4079a80721c861d0663dc8717e/django/utils/html.py#L85-L102). There's no need to write JS at all to pass those values to the JS and it might be problematic with CSP as well.

**Comment by tomusher** [comment]
Agreed this would be a big improvement!
