### ISSUE TITLE
preview screen

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail-ai#78]
If you use the magic want the text is replaced. This is nice but it would be more nice if you would get a popup with a split screen or something to see what has been changed on you text. And only if you sure you accept the changes.
Would it be possible to make this popup so that it works with a diff. Like git conflicts and you need to merge it ? Then you can accept a rewrite line per line if needed :)

**Comment by tomusher** [comment]
Thanks @onno-timmerman! I think we'll be covering this as part of #60 #61 and #62, but if you're thinking of something else please feel free to reopen.
