### ISSUE TITLE
bug gpt-3.5-turbo, gpt-4

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail-ai#80]
When I use gpt-3.5-turbo or gpt-4 it works but when using gpt-4-0125-preview or other models it always gives me an error {"error": "An unexpected error occurred."}

Changing to gpt-3.5-turbo or gpt-4 works.

**Comment by laymonage** [comment]
If you use other models, need to define the `TOKEN_LIMIT` in the settings: https://wagtail-ai.readthedocs.io/latest/ai-backends/#using-a-custom-openai-or-openai-compatible-model

The only known models are:
https://github.com/wagtail/wagtail-ai/blob/4fa9b396fa18933f1de6b5a65d1f4da4ace26716/src/wagtail_ai/tokens.py#L12-L22

For other models, refer to the context window value from: https://platform.openai.com/docs/models/
